spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"

server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka