spring.application.name: RestaurantService
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/rest?currentSchema=public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: rest
    bootstrap-servers: localhost:9092

server:
  port: 8084