spring.application.name: order-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/orderdb?currentSchema=public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: order
    bootstrap-servers: localhost:9092

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

resilience4j:
  circuitbreaker:
    instances:
      orderServiceToPaymentCircuitBreaker:
        waitDurationInOpenState: 5000ms
        #Время ожидания в открытом состоянии
        failureRateThreshold: 50
        #процент ошибок
        eventConsumerBufferSize: 10
        #количество событий, которые будут храниться в памяти
        recordExceptions:
          - org.apache.kafka.common.errors.TimeoutException
          - java.io.IOException
      orderServiceToRestCircuitBreaker:
        waitDurationInOpenState: 5000ms
        #Время ожидания в открытом состоянии
        failureRateThreshold: 50
        #процент ошибок
        eventConsumerBufferSize: 10
        #количество событий, которые будут храниться в памяти
        recordExceptions:
          - org.apache.kafka.common.errors.TimeoutException
          - java.io.IOException
